namespace ComunaClick.Api.Modules.Crm.Contracts;

public sealed record BuyerProfessionalProfileResponse(
    bool HasProfile,
    Guid? ProfessionalId,
    string? Name,
    string? Email,
    string? Phone,
    string? Specialty,
    string? Bio,
    bool IsVerified,
    bool IsActive,
    string? WebsiteUrl = null,
    string? InstagramUrl = null,
    string? FacebookUrl = null,
    string? LinkedInUrl = null,
    string? XUrl = null,
    string? TikTokUrl = null,
    string? YouTubeUrl = null,
    string? OtherLinkLabel = null,
    string? OtherLinkUrl = null,
    string? BannerUrl = null,
    string? ProfilePhotoUrl = null,
    long ProfileViewCount = 0,
    string? CertificationsJson = null);
