// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RazorIdentity.Data;

#nullable disable

namespace RazorIdentity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427222137_AddPmoAvFisicoTables")]
    partial class AddPmoAvFisicoTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PmoVectorFinancieroRowSequence");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.Montecarlo.MontecarloProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TabsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MontecarloProjects");
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoFinancieroSap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ad")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("AD");

                    b.Property<string>("CentroCostoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("centro_costo_nombre");

                    b.Property<decimal>("Cl")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("CL");

                    b.Property<decimal>("Ct")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("CT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Em")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("EM");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("GrupoVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grupo_version");

                    b.Property<decimal>("Ic")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("IC");

                    b.Property<string>("IdSap")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("id_sap");

                    b.Property<decimal>("Ie")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("IE");

                    b.Property<decimal>("Mo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("MO");

                    b.Property<DateOnly?>("Periodo")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<decimal>("Sc")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("SC");

                    b.Property<string>("VersionSap")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version_sap");

                    b.HasKey("Id");

                    b.HasIndex("Periodo");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("IdSap", "ProyectoId")
                        .IsUnique();

                    b.ToTable("financiero_sap", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoVcProject9c", b =>
                {
                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("IdC9")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_c9");

                    b.Property<decimal>("Base")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("base");

                    b.Property<decimal>("Cambio")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("cambio");

                    b.Property<string>("CatVp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cat_vp");

                    b.Property<decimal>("Compromiso")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("compromiso");

                    b.Property<decimal>("Control")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("control");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Eat")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("eat");

                    b.Property<decimal>("Financiero")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("financiero");

                    b.Property<decimal>("Incurrido")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("incurrido");

                    b.Property<int>("MonedaBase")
                        .HasColumnType("integer")
                        .HasColumnName("moneda_base");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<decimal>("PorComprometer")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("por_comprometer");

                    b.Property<decimal>("Tendencia")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("tendencia");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProyectoId", "IdC9");

                    b.HasIndex("ProyectoId", "Periodo");

                    b.ToTable("vc_project_9c", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"PmoVectorFinancieroRowSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("CatVp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cat_vp");

                    b.Property<string>("CentroCosto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("centro_costo");

                    b.Property<string>("DetalleFactorial")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle_factorial");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("monto");

                    b.Property<DateOnly>("Periodo")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerAnalisis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoProyecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaEjercicio")
                        .HasColumnType("date");

                    b.Property<int>("Iteraciones")
                        .HasColumnType("integer");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultadosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RevisionRiesgosId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SemillaAleatoria")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("TallerAnalisis");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapexUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CompometidoUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimadoTerminoUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric(20,15)");

                    b.Property<Guid?>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("FechaTasaCambio")
                        .HasColumnType("date");

                    b.Property<string>("NombrePaquete")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorComprometidoUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("TallerContratos");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ProyectoId", "Rut")
                        .IsUnique();

                    b.ToTable("TallerEmpresas");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerFamilia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("TallerFamilias");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Amenazas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Clase")
                        .HasColumnType("numeric");

                    b.Property<string>("ClaseEstimacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Consideraciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostoClpOverride")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CostoUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsCerteza")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxKusd")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MaxPct")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MinKusd")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MinPct")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Oportunidades")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProbableKusd")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ProbablePct")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SubPartida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ViaRiesgo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("TallerItems");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerMcResultado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CdfJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<double>("DesvStd")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistogramaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemMediasJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Iteraciones")
                        .HasColumnType("integer");

                    b.Property<double>("Media")
                        .HasColumnType("double precision");

                    b.Property<double>("P10")
                        .HasColumnType("double precision");

                    b.Property<double>("P50")
                        .HasColumnType("double precision");

                    b.Property<double>("P80")
                        .HasColumnType("double precision");

                    b.Property<double>("P90")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("TallerMcResultados");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("FechaEjercicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Organizacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TallerProyectos");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerRevisionRiesgos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroRevision")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("TallerRevisionesRiesgos");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerRiesgo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoRiesgo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("EsOportunidad")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ImpactoMaxUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ImpactoMinUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ImpactoProableUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ItemViaRiesgoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotasCambio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Probabilidad")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("TallerRiesgos");
                });

            modelBuilder.Entity("RazorIdentity.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BioOrNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Country")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OtherLinks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegionOrState")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoApiAcumulada", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("api_acumulada", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoApiParcial", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("api_parcial", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoNpcAcumulado", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("npc_acumulado", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoNpcParcial", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("npc_parcial", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoRealAcumulado", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("real_acumulado", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoRealParcial", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("real_parcial", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoV0Acumulada", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("v0_acumulada", (string)null);
                });

            modelBuilder.Entity("RazorIdentity.Models.PmoFinance.PmoV0Parcial", b =>
                {
                    b.HasBaseType("RazorIdentity.Models.PmoFinance.PmoVectorFinancieroRow");

                    b.HasIndex("ProyectoId");

                    b.ToTable("v0_parcial", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerAnalisis", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerProyecto", "Proyecto")
                        .WithMany("Analisis")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerContrato", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerEmpresa", "Empresa")
                        .WithMany("Contratos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerFamilia", "Familia")
                        .WithMany("Contratos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerProyecto", "Proyecto")
                        .WithMany("Contratos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Familia");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerEmpresa", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerProyecto", "Proyecto")
                        .WithMany("Empresas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerFamilia", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerProyecto", "Proyecto")
                        .WithMany("Familias")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerItem", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerContrato", "Contrato")
                        .WithMany("Items")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerMcResultado", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerContrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerRevisionRiesgos", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerProyecto", "Proyecto")
                        .WithMany("Revisiones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerRiesgo", b =>
                {
                    b.HasOne("RazorIdentity.Models.TallerCostos.TallerRevisionRiesgos", "Revision")
                        .WithMany("Riesgos")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerContrato", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerEmpresa", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerFamilia", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerProyecto", b =>
                {
                    b.Navigation("Analisis");

                    b.Navigation("Contratos");

                    b.Navigation("Empresas");

                    b.Navigation("Familias");

                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("RazorIdentity.Models.TallerCostos.TallerRevisionRiesgos", b =>
                {
                    b.Navigation("Riesgos");
                });
#pragma warning restore 612, 618
        }
    }
}
