<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ComunaClick.Common\ComunaClick.Common.csproj" />
    <ProjectReference Include="..\ComunaClick.Shared\ComunaClick.Shared.csproj" />
    <ProjectReference Include="..\ComunaClick.SharedUI\ComunaClick.SharedUI.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RootNamespace>ComunaClick.App</RootNamespace>
  </PropertyGroup>

</Project>
